image: Visual Studio 2019

environment:
  JAVA_HOME: 'C:\Program Files (x86)\Java\jdk1.8.0'
  APPVEYOR_TOKEN:
    secure: vl0Tyf7ckkyu3xLXvwbRSdZjt6AdKd3gtvs1Ukiegcc=

install:
  - ps: Invoke-RestMethod -Method Get -Uri https://ci.appveyor.com/api/projects/dgregory084/physfs-jni/artifacts/target/release/physfs_jni.dll?branch=master -OutFile physfs_jni.dll -Headers @{ "Authorization" = "Bearer $APPVEYOR_TOKEN" }

build_script:
  - cmd: .\gradlew.bat build

on_success:
  - cmd: .\gradlew.bat jacocoTestReport
  - cmd: .\gradlew.bat --stop

artifacts:
  - path: build\reports\tests\test
    name: JUnit Test Report
  - path: build\reports\jacoco\test
    name: Jacoco Coverage Report


cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.gradle\caches'
  - '%USERPROFILE%\.gradle\wrapper -> gradlew.bat'
  - '%USERPROFILE%\.gradle\build-cache'
