image: Visual Studio 2019

environment:
  JAVA_HOME: 'C:\Program Files (x86)\Java\jdk1.8.0'
  RUST_BACKTRACE: "1"
  RUSTFLAGS: "-C target-feature=+crt-static"

install:
  - cinst llvm --x86
  - ps: Invoke-WebRequest -Uri https://win.rustup.rs/i686 -OutFile rustup-init.exe
  - cmd: .\rustup-init.exe -y --profile minimal --default-toolchain stable --default-host i686-pc-windows-msvc
  - ps: Set-Item -Path env:PATH -Value ($env:PATH + ";" + $env:USERPROFILE + "\.cargo\bin")

build_script:
  - cmd: cd launcher
  - cmd: cargo build
  - cmd: cargo build --release

test_script:
  - cmd: cd launcher
  - cmd: cargo test

artifacts:
  - path: launcher/target/release/openil2.exe
    name: OpenIL2 Launcher
  - path: launcher/target/debug/openil2.exe
    name: OpenIL2 Launcher (Debug Mode)

cache:
  - '%USERPROFILE%\.cargo'
