image: Visual Studio 2019

environment:
  RUST_BACKTRACE: "1"
  RUSTFLAGS: "-C target-feature=+crt-static"

install:
  - cinst llvm --x86
  - cinst adoptopenjdk11 --x86 --params="/ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome /INSTALLDIR=%ProgramFiles%\AdoptOpenJDK"
  - cmd: refreshenv
  - ps: Invoke-WebRequest -Uri https://win.rustup.rs/i686 -OutFile rustup-init.exe
  - cmd: .\rustup-init.exe -y --profile minimal --default-toolchain stable --default-host i686-pc-windows-msvc
  - ps: Set-Item -Path env:PATH -Value ($env:PATH + ";" + $env:USERPROFILE + "\.cargo\bin")

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\launcher
  - cmd: cargo build
  - cmd: cargo build --release

  - cmd: cd %APPVEYOR_BUILD_FOLDER%\physfs_jni
  - cmd: cargo build
  - cmd: cargo build --release

  - cmd: copy /y %APPVEYOR_BUILD_FOLDER%\physfs_jni\target\release\physfs_jni.dll %APPVEYOR_BUILD_FOLDER%\physfs_java
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: .\gradlew.bat :physfs_java:jar

  - cmd: iscc /O%APPVEYOR_BUILD_FOLDER%\output %APPVEYOR_BUILD_FOLDER%\installer\openil2-debug.iss
  - cmd: iscc /O%APPVEYOR_BUILD_FOLDER%\output %APPVEYOR_BUILD_FOLDER%\installer\openil2.iss

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\launcher
  - cmd: cargo test

  - cmd: cd %APPVEYOR_BUILD_FOLDER%\physfs_jni
  - cmd: cargo test

  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: .\gradlew.bat :physfs_java:test
  - cmd: .\gradlew.bat :physfs_java:jacocoTestReport

on_finish:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: .\gradlew.bat --stop

artifacts:
  - path: installer\output\openil2-installer-debug.exe
    name: OpenIL2 Installer (Debug Mode)

  - path: installer\output\openil2-installer.exe
    name: OpenIL2 Installer

  - path: launcher\target\release\openil2.exe
    name: OpenIL2 Launcher
  - path: launcher\target\debug\openil2.exe
    name: OpenIL2 Launcher (Debug Mode)

  - path: physfs_jni\target\release\physfs_jni.dll
    name: PhysFS JNI DLL
  - path: physfs_jni\target\debug\physfs_jni.dll
    name: PhysFS JNI DLL (Debug Mode)

  - path: physfs_java\build\libs\physfs_java.jar
    name: PhysFS Java JAR
  - path: physfs_java\build\reports\tests\test
    name: PhysFS Java JUnit Test Report
  - path: physfs_java\build\reports\jacoco\test
    name: PhysFS Java Jacoco Coverage Report

cache:
  - '%USERPROFILE%\.cargo'
  - '%USERPROFILE%\.gradle\caches'
  - '%USERPROFILE%\.gradle\wrapper'
