image: Visual Studio 2019

environment:
  APPVEYOR_TOKEN:
    secure: vl0Tyf7ckkyu3xLXvwbRSdZjt6AdKd3gtvs1Ukiegcc=

install:
  - cinst jdk8 --x86
  - ps: Invoke-RestMethod -Method Get -Uri https://ci.appveyor.com/api/projects/dgregory084/physfs-jni/artifacts/target/release/physfs_jni.dll?branch=master -OutFile lib\physfs_jni.dll -Headers @{ "Authorization" = "Bearer $APPVEYOR_TOKEN" }

build_script:
  - cmd: .\gradlew.bat build

test_script:
  - cmd: .\gradlew.bat test --stacktrace

on_success:
  - cmd: .\gradlew.bat --stop

cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.gradle\caches'
  - '%USERPROFILE%\.gradle\wrapper -> gradlew.bat'
  - '%USERPROFILE%\.gradle\build-cache'
