.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build

before_script:
  - choco install -y jdk8 --x86
  - wget -O lib\physfs_jni.dll https://gitlab.com/DavidGregory084/physfs_jni/-/jobs/artifacts/master/raw/target/release/physfs_jni.dll?job=build

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - ./gradlew build
    - ./gradlew test
