.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

variables:
  CARGO_HOME: %CI_PROJECT_DIR%\cargo

stages:
  - build

before_script:
  - choco install -y jdk8 --x86
  - curl -o rustup-init.exe https://win.rustup.rs/i686
  - .\rustup-init.exe -y --profile minimal --default-toolchain stable --default-host i686-pc-windows-msvc
  - set PATH='%PATH%;%CARGO_HOME%\bin'

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - cargo +stable-i686-pc-windows-msvc build --verbose
    - cargo +stable-i686-pc-windows-mscv test --verbose
