.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build

before_script:
  - choco install -y jdk8 --x86
  - Set-Item -path env:CARGO_HOME -value ($env:CI_PROJECT_DIR + "\cargo")
  - Write-Output $env:CARGO_HOME
  - curl -o rustup-init.exe https://win.rustup.rs/i686
  - .\rustup-init.exe -y --profile minimal --default-toolchain stable --default-host i686-pc-windows-msvc
  - Set-Item -path env:PATH -value ($env:PATH + ";" + $env:CARGO_HOME + "\bin")
  - Write-Output $env:PATH

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - cargo +stable-i686-pc-windows-msvc build --verbose
    - cargo +stable-i686-pc-windows-mscv test --verbose
