.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

variables:
  RUST_BACKTRACE: "1"

stages:
  - test
  - build
  - deploy

before_script:
  - choco install -y jdk8 --x86
  - choco install -y llvm --x86
  - Set-Item -path env:CARGO_HOME -value ($env:CI_PROJECT_DIR + "\cargo")
  - Set-Item -path env:PATH -value ($env:PATH + ";" + $env:CARGO_HOME + "\bin")
  - curl -o rustup-init.exe https://win.rustup.rs/i686
  - .\rustup-init.exe -y --profile minimal --default-toolchain stable --default-host i686-pc-windows-msvc

test:
  extends:
    - .shared_windows_runners
  stage: test
  script:
    - cargo build --verbose
    - cargo test --verbose

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target\release\physfs_jni.dll
  trigger:
    project: DavidGregory084/il2-physfs
    branch: master
