[package]
name = "sfs"
version = "0.1.0"
authors = ["David Gregory <davidgregory084@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause-Patent"

[lib]
name = "sfs"
crate-type = ["lib"]

[dependencies]
memmap = "0.7"
nom = "6"
rayon = "1.5"
flate2 = "1"
jni = "0.18"
anyhow = "1"
indicatif = "0.15"