image: Visual Studio 2019

environment:
  JAVA_HOME: 'C:\Program Files (x86)\Java\jdk1.8.0'
  APPVEYOR_TOKEN:
    secure: vl0Tyf7ckkyu3xLXvwbRSdZjt6AdKd3gtvs1Ukiegcc=

build_script:
  - cmd: .\gradlew.bat build

on_success:
  - cmd: .\gradlew.bat --stop

artifacts:
  - path: build\libs\il2-classload-agent.jar
    name: Java Agent JAR

cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.gradle\caches'
  - '%USERPROFILE%\.gradle\wrapper -> gradlew.bat'
  - '%USERPROFILE%\.gradle\build-cache'
